import torch
import nltk
from nltk.corpus import stopwords
from pathlib import Path

try:
    ALL_STOPWORDS = set(stopwords.words("arabic") + stopwords.words("english"))
except:
    nltk.download("stopwords")
    ALL_STOPWORDS = set(stopwords.words("arabic") + stopwords.words("english"))

TD_DB = "demo_user"

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

RANDOM_STATE = 42

BASE_DIR = Path(__file__).parents[1]

DATA_PATH = BASE_DIR / "data"

GPC_PATH = DATA_PATH / "gpc_sample.xlsx"

TRAIN_VAL_DATA_PATH = DATA_PATH / "train_val.csv"

TRAIN_CLEANED_DATA_PATH = DATA_PATH / "train_cleaned.csv"

VALIDATION_DATA_PATH = DATA_PATH / "validation.csv"

TEST_DATA_PATH = DATA_PATH / "test.csv"

FULL_DATA_SET_DATA_PATH = DATA_PATH / "full_dataset.csv"

CLEANED_TEST_DATA_PATH = DATA_PATH / "cleaned_test.csv"

CLEANED_TRAIN_DATA_PATH = DATA_PATH / "cleaned_train.csv"

CLEANED_FULL_DATASET_DATA_PATH = DATA_PATH / "cleaned_full_dataset.csv"

GPC_PATH = DATA_PATH / "GPC.xlsx"

CLEANED_GPC_PATH = DATA_PATH / "cleaned_gpc.csv"

PRODUCT_TEST_EMBEDDINGS_PATH = DATA_PATH / "product_test_embeddings.csv"

PRODUCT_TRAIN_EMBEDDINGS_PATH = DATA_PATH / "product_train_embeddings.csv"

PRODUCT_FULL_DATASET_EMBEDDINGS_PATH = DATA_PATH / "product_full_dataset_embeddings.csv"

PRODUCT_FULL_DATASET_EMBEDDINGS__QWEN_PATH  = DATA_PATH / "product_full_dataset_embeddings_qwen.csv"

CLASS_EMBEDDINGS_PATH = DATA_PATH / "class_embeddings.csv"

CLASS_EMBEDDINGS_PATH_QWEN = DATA_PATH / "class_embeddings_qwen.csv"

CONFIG_PATH = BASE_DIR / "config"

E5_LARGE_INSTRUCT_CONFIG_PATH = CONFIG_PATH / "e5_large_instruct_config.json"

OPUS_TRANSLATION_CONFIG_PATH = CONFIG_PATH / "opus_translation_config.json"

FALCON3_7B_CONFIG_PATH = CONFIG_PATH / "falcon3_7B_config.json"

QWEN3_8B_CONFIG_PATH = CONFIG_PATH / "qwen3_8B.json"

ENV_PATH = CONFIG_PATH / ".env"

MODEL_PATH = BASE_DIR / "models"

CLASSES_TRANSLATION = {
    "baby care": "العناية بالرضع",
    "bakery": "المخبوزات",
    "beef lamb meat": "لحم البقر والضأن",
    "beef processed meat": "لحم البقر واللحوم المصنعة",
    "biscuits cakes": "البسكويت والكيك",
    "candles air fresheners": "الشموع ومعطرات الجو",
    "chips crackers": "رقائق البطاطس والمقرمشات",
    "chips crackers": "رقائق البطاطس والمقرمشات",
    "chocolates sweets desserts": "الشوكولاتة والحلويات والحلويات الجاهزة",
    "cleaning supplies": "مستلزمات التنظيف",
    "condiments dressings marinades": "التوابل والصلصات والمخللات",
    "cooking ingredients": "مكونات الطبخ",
    "dairy eggs": "الألبان والبيض",
    "disposables napkins": "المنتجات أحادية الاستخدام والمناديل",
    "fruits": "الفواكه",
    "furniture": "الأثاث",
    "hair shower bath soap": "العناية بالشعر والاستحمام والصابون",
    "home appliances": "الأجهزة المنزلية",
    "home textile": "المنسوجات المنزلية",
    "jams spreads syrups": "المربى والدهن والشراب",
    "nuts dates dried fruits": "المكسرات والتمر والفواكه المجففة",
    "personal care skin body care": "العناية الشخصية والعناية بالبشرة والجسم",
    "poultry": "الدواجن",
    "rice pasta pulses": "الأرز والمعكرونة والبقوليات",
    "sauces dressings condiments": "الصلصات والتتبيلات والتوابل",
    "soft drinks juices": "المشروبات الغازية والعصائر",
    "sweets desserts": "الحلويات والتحليات",
    "tea and coffee": "الشاي والقهوة",
    "tea coffee hot drinks": "الشاي والقهوة والمشروبات الساخنة",
    "tins jars packets": "المعلبات والعبوات",
    "vegetables fruits": "الخضروات والفواكه",
    "vegetables herbs": "الخضروات والأعشاب",
    "water": "المياه",
    "laundry detergents": "الغسيل والمنظفات",
    "sugar home baking": "السكر والمخبوزات المنزلية",
    "perfumes deodorants": "العطور ومزيلات العرق",
    "stationary": "اللوازم المكتبية",
    "breakfast cereals bars": "ألواح حبوب الإفطار",
    "dental care": "العناية بالأسنان",
    "fish": "الأسماك",
    "footwear": "الأحذية",
    "mobile tablets": "الأجهزة اللوحية",
    "party supplies and gifts": "مستلزمات الحفلات والهدايا",
    "pets care": "العناية بالحيوانات الأليفة",
    "wear": "الملابس"
}

ALL_BRANDS = {
    "AL Karama",
    "سفن اب",
    "جلاكسي فلوتس",
    "ودس",
    "كلوريل",
    "قليه",
    "إيزيس",
    "اكو فينا",
    "الرشيدي",
    "Ponky",
    "coca-cola",
    "برنجلز",
    "مارو",
    "الدره",
    "بيك رولز",
    "اميريكانا ",
    "دوريتوس",
    "ALMARAI",
    "Trust",
    "WALKERS",
    "Bisco Datto",
    "Twinkies",
    "تيفاني بيج بريك",
    "ساند",
    "Elano",
    "Durra",
    "بشاير",
    "سنبلة",
    "اكسير",
    "Puidor ",
    "روشين",
    "Arabic",
    "المراعي",
    "العراب",
    "فارم فريش ",
    "بونو",
    "Coca-Cola",
    "فيتنس",
    "جاردينيو",
    "Nesquik",
    "A.M.R",
    "Raw",
    "pringles",
    "Slite",
    "السوهاجى",
    "بروانيز",
    "Bounty",
    "حلوانى",
    "جودداى",
    "ميجا شيبس",
    "CRYSTAL",
    "اوليو",
    "Fisherman",
    "Corona",
    "Taste",
    "HEINZ",
    "باشاك ",
    "LAMAR",
    "أميريكان جاردن",
    "هوبي لايف",
    "نوليدو",
    "Merba",
    "رويال جالا",
    "المدينة",
    "May Gold",
    "Basma",
    "عاينز",
    "MegaChips",
    "سيجافريدو",
    "روستو",
    "بست فريش",
    "كلوركس",
    "تتراباك",
    "بلندي",
    "ريحانة",
    "ISIS",
    "Mexicana",
    "Wrigley",
    "ايطاليانو",
    "فيجن",
    "المزرعة",
    "كلورتس",
    "اورويو",
    "lamar",
    "ALOE VERA",
    "الوفيرا كينج",
    "داوني",
    "عبور",
    "zamzam",
    "Rauch",
    "شيبسانو",
    "فرازه",
    "حياه",
    "ديزني",
    "ايزي كير",
    "Cola",
    "سكيتلس",
    "Daria",
    "فيفا",
    "لامى",
    "Atyab",
    "كير",
    "Galaxy",
    "Al wadi al akhdar",
    "halwani",
    "Louisiana",
    "اكوا فينا",
    "دولفن جولد",
    "El Hanim",
    "Guylian",
    "أبو عوف",
    "Tiffany Big Break",
    "Live Green",
    "ل\\ابوعوف",
    "الادهم",
    "جلاكسي",
    "هابنز",
    "alsuhagy",
    "ساكلا",
    "Munchos",
    "لاجو بوكر",
    "حوار",
    "Ariel",
    "Daily Fresh",
    "DOMTY",
    "بوريو",
    "العمار",
    "المطبخ",
    "Vent",
    "بيكو",
    "Lixir",
    "صوفيا",
    "shicketita",
    "ماك سوس",
    "El Salam",
    "Schweppes",
    "YAMAMA",
    "بيبسى",
    "الملكة",
    "فيرى",
    "زياده",
    "سابان",
    "HAYAT",
    "اليامن",
    "Farmers Market",
    "ايزى كوك",
    "Basak ",
    "دره",
    "El Bawady",
    "أوليو",
    "Mc Sauce",
    "MR.KRISPS",
    "Al Rabie",
    "السنبله",
    "El Shamadan Katakito",
    "نستله فتنس",
    "هاريبو",
    "أكوافينا",
    "Bisco Misr",
    "جياردينو",
    "بريك تي",
    "هاينمز ",
    "ion",
    "ديلي",
    "Sekem",
    "اجرومنت",
    "دوريتس",
    "Isis",
    "كريستال",
    "lind",
    "Ilou",
    "اوزمو هوب",
    "لنمار",
    "Shahia ",
    "البداره",
    "بارفيا",
    "توليدو",
    "تشكلتس",
    "هيرمان",
    "تست",
    "فيبا",
    "لونج شيبس",
    "Emirates Pofaki",
    "BOSTANY ",
    "كادبوري",
    "al ain",
    "بريتزو",
    "كنز",
    "GANDOUR",
    "اكسترا",
    "أيون",
    "Kinder Happy Hippo",
    "ديفاتول",
    "لذه",
    "لينو",
    "Dasani",
    "Fun Day",
    "كايزن",
    "Farm Frites",
    "TODO",
    "الوردة",
    "Kiri",
    "Sunbites",
    "سول",
    "ماي",
    "Rene",
    "شيبسى",
    "The farm",
    "Fayrouz",
    "Roshen",
    "روست",
    "DANETTE",
    "EL Sahaba",
    "فايف مينتس",
    "توريست",
    "توينكيز",
    "El Haloub",
    "EXTRA FOOD",
    "فراره",
    "روستي",
    "جرين لايف",
    "فود لافر",
    "الليحيمى",
    "مصرية",
    "مامز فوود",
    "احمد تى",
    "غالية",
    "Afia ",
    "كولد ستون",
    "Mcvities Digestive",
    "Farm Fresh",
    "ChipsySuper",
    "Vegeta ",
    "ايلوو",
    "زاهر",
    "راند",
    "عبدالمعبود",
    "فن داي",
    "فرسكا",
    "مارس",
    "LACTEL",
    "ماي تونة",
    "AloeVera King Drink",
    "El Rashidi El Mizan",
    "Nescafe",
    "Afia",
    "AL HAYAT",
    "ماونتن ديو",
    "ووندر فيل",
    "ماجي",
    "مكتيفز",
    "Comfort",
    "دانيت",
    "Al Walima",
    "سافكول",
    "بيور ايج",
    "El Rashidi El Asly",
    "دناو",
    "Repo",
    "Ahmad Tea",
    "Solen Ozmo",
    "كرما",
    "شيبسي",
    "نسله",
    "El Arosa",
    "نستلة",
    "Crazy Lemon",
    "Borges",
    "مونارك",
    "Lotus ",
    "FISHERMAN",
    "GREEN LAND",
    "كوكس",
    "إم أند إمز",
    "شهرزاد",
    "شوتس",
    "وادي",
    "بيتلا",
    "daria ",
    "Meat Land",
    "امار",
    "ماى جولد",
    "كرنفال",
    "سيدرا",
    "روسو",
    "تشكيله",
    "Altahya ",
    "حلوب زمان",
    "Kitkat",
    "Knorr",
    "Sweet Life",
    "مكة",
    "Extra",
    "ميرو",
    "كوكي",
    "تلال ",
    "بسمة",
    "جنرال",
    "Fern",
    "درة",
    "كاليفورنيا جاردن",
    "بيت الخير",
    "جواهر",
    "فريش فارم",
    "Dano",
    "Tolido ",
    "بيتى",
    "Karim ",
    "Loacker",
    "اكوا دلتا",
    "جلاسي",
    "Sunbulah",
    "اسينشال ايفري داي",
    "انسام",
    "ريو ماري",
    "جهينهه",
    "Squeeze ",
    "المراعى",
    "لايف جرين",
    "Mobi",
    "ILOU",
    "فرسان",
    "Al Halawani",
    "لايون،",
    "Happy",
    "لافاش",
    "صاني",
    "El Helal",
    "كيكومان",
    "NESTLE",
    "بيتي",
    "ربيع",
    "بنزانى",
    "اولكر دايجستيف",
    "Mr Muscle",
    "WADI FOOD",
    "Amanda ",
    "katilo",
    "اوسكار",
    "ريجينا",
    "ببيتو",
    "ابو طارق",
    "هاى برو",
    "كيرى",
    "Mars",
    "Yamani",
    "American Garden",
    "باريلا",
    "Freyma'S",
    "TIPO",
    "شهد",
    "توشيبا",
    "بيك ستيكس",
    "كادبوري بابلي",
    "الهنا",
    "ربتش بيك",
    "جراند",
    "الصالحيه",
    "ادد مي ",
    "DANISA",
    "Red bull",
    "GOOD FRANCE",
    "بريزيدون",
    "كوكى",
    "Lindor",
    "سيكم",
    "Koki",
    " Top Value",
    "هايبروان",
    "لامدى",
    "تمرى",
    "ميتلاند",
    "كولا",
    "ام اى ار",
    "El Shamadan",
    "CLASS A",
    "لمبادا",
    "Free Go",
    "Chipsy",
    "لمتنا",
    "دبل ديرى",
    "مزارع دينا",
    "باندورا",
    "لوتس",
    "ريتش بيك",
    "فيرن",
    "بريزدنت",
    "كويك ميلك",
    "Mackintosh’s",
    "FREYMAS",
    "لامار",
    "Healthy milk",
    "شيبس",
    "Power Horse",
    "ميلك لاند",
    " تي سي بوي",
    "Red Bull",
    "دساني",
    "فريدا",
    "اطياب",
    "كمارا",
    "تمري",
    "زينه",
    "Squeezemangopine",
    "ايزيس",
    "فلو",
    "safi",
    "قتيلو",
    "فيجيتار فاين فودز",
    "ريتر سبورت",
    "Dina Farms",
    "كاكاو لافرز",
    "ايون",
    "نسكافيه",
    "شيخون",
    "Bake Rich",
    "ريتش",
    "فرانسيسكو رينالدي",
    "IMTENAN",
    "فاين",
    "دولفين",
    "Doha",
    "مكفينز",
    "Ulker",
    "بسكريم",
    "شيبسى فورنو",
    "Nestle Fitness",
    "فرجللو",
    "فريرو",
    "Nour",
    "بربيكان",
    "المتحده",
    "VIDAL",
    "مستر كريسبس65ج",
    "ION",
    "Halwani Bros",
    "العروسه",
    "Haday",
    "كينج ام",
    "جراند كافيه",
    "تيارا",
    "Taza ",
    "الفتح",
    "RAZZ",
    "Gandour",
    "غلاوة",
    "أحمد تي",
    "هي شون يوان",
    "اورنت",
    "امادا",
    "Dairy Milk",
    "زي جو",
    "بيور",
    "جهينع",
    "نستله كرنفاليتا",
    "Leibniz",
    "هيت",
    "أجرومونتي ",
    "اورينتال",
    "تيفاني بريك ريزو",
    "جاردينو",
    "Olitalia",
    "fresh source",
    "Super Ring",
    "Qaleya",
    "فيري",
    "مورا",
    "Hala",
    "kitkat",
    "nan",
    "ام اند امز",
    "ميكس",
    "Lino",
    "ماشا اند كيه",
    "شيبسى صن بايتس",
    "رودس",
    "الضحي",
    "ان سى",
    "LION",
    "كوكاكولا",
    "GIMOKA",
    "Lavie",
    "نمره 1",
    "جهينه",
    "Good French",
    "امستل",
    "الأصيل",
    "Sprite",
    "سامى سلامه",
    "الاصلي ",
    "ضيافة",
    "Break",
    "شوجتين",
    "السنبلة",
    "بونجورنو",
    "NOSH",
    "Montana",
    "Domty",
    "King",
    "كاليفورنيا  ",
    "ايجلو",
    "Kuhne",
    "راز",
    "شي فودج",
    "اكوا",
    "إم سي",
    "Lipton",
    "علي كيفك",
    "افانتي",
    "شيبسى رو",
    "ماكفتيز",
    "Cheetos",
    "أمريكانا",
    "بيريل",
    "ايرو",
    "DASANI",
    "Benson",
    "فراجيلو",
    "MCVITIES THINS",
    "مانا",
    "مستر مسلز",
    "باولا",
    "Coco Lovers",
    "Chtaura",
    "ريد",
    "العطار",
    "Yamama",
    "فيريرو",
    "قويدر",
    "Paladin",
    "VASO",
    "كندوز",
    "الكرامه",
    "فيشر مان",
    "دولسي دولسيكا",
    "Shahrazad",
    "دريتوس",
    "Clorets",
    "regina",
    "NESCAFE",
    "SQUEEZE ",
    "الاسطوره",
    "غندور",
    "Bravo",
    "Al Tahya",
    "اوريو",
    "مانشوز45جم",
    "الطاهيه",
    "ديمه",
    "ديتول",
    "توب اوف ذا بوب",
    "سورس",
    "لامدي",
    "البوادى",
    "افانتى",
    "Dobella ",
    "Dango",
    "Healthy",
    "El Sahaba",
    "Adio",
    "red bull",
    "Windows",
    "اوتيما",
    "Mitco",
    "جوسى",
    "Vegeeta",
    "El Aseel",
    "Al Tahhan",
    "ايليت",
    "حواء",
    "جيكار",
    "Queen",
    "Skittles",
    "Fisherman ",
    "Oreo",
    "سبينس",
    "اكوفينا",
    "milka",
    "اكسون",
    "دريا",
    "RICH",
    "دانون",
    "Givrex",
    "Heinz",
    "نسئله",
    "باندا",
    "هنية",
    "توليدو ",
    "رنا",
    "Cadbury",
    "COVERTINA",
    "Hawaa",
    "برنجز",
    "سويس شويس",
    "Metco",
    "Lulu",
    "Al Watania",
    "Paradise",
    "Yes",
    "اويكو",
    "شهية",
    "مصر كافيه",
    "Harvest ",
    "OBOUR LAND",
    "Wadi",
    "مكفتيز دايجستيف",
    "كينج إم",
    "شهي",
    "عافيه",
    "CRF",
    "Al Doha",
    "Cono",
    "Rialto",
    "بست بيور",
    "مكفتيزالشوفان",
    "فريكو",
    "اميريكان جاردن",
    "اوليفيتا",
    "زوان",
    "Coca Cola",
    "سندباد",
    "صن شاين ",
    "Italiano",
    "California",
    "Al Wadi",
    "DIATOASTA",
    "فورنو",
    "Uludag",
    "Taste Pure",
    "السوهاجي",
    "ثري شيفس ",
    "بسمه",
    "كوكاولا",
    "لورينز",
    "فيروز",
    "سلايت",
    "Astonish",
    "Gebnety",
    "Carrefour",
    "كيروكس",
    "تيفاني بريك",
    "وطنية",
    "هايبر وان",
    "نستله كوالتى ستريت",
    "هاربيك",
    "اشهى",
    "ريد بل",
    "كادبورى",
    "Molto",
    "Arafa",
    "كيت كات ",
    "لودفيك",
    "Twist & Drink",
    "Flying Goose",
    "الممتاز",
    "البيلا",
    "فيمتو",
    "temry",
    "Frozen",
    "كولا ",
    "فودى",
    "ستروب وافل",
    "FUN DAY",
    "لودويك",
    "BREAK",
    "Freez",
    "Anchor",
    "ثري شيفس",
    "الوادي ",
    "كتاكيتو",
    "LuLu",
    "Dettol",
    "تيفاني",
    "هالى",
    "برينجلز",
    "Tiger",
    "الرشيدى",
    "بافاريا",
    "Rabea",
    "Barbican",
    "Telal",
    "JUHAYNA",
    "روبكس",
    "لمار",
    "فلفيتا",
    "PERSIL",
    "لولو",
    "Rich",
    "Dili",
    "الميزان",
    "تريند",
    "باونتى",
    "بكر",
    "اكسبشن",
    "Dilmah",
    "ميليتا",
    "Add Me",
    "beyti",
    "FARAGELLO",
    "سفن أب",
    "جرين هاوس",
    "كورونا",
    "كنور",
    "هيلني ميلك",
    "بريد واى",
    "بريزدون",
    "Choice",
    "Rehana",
    "سن توب",
    "كليو",
    "BARAKA",
    "Crunchy",
    "الهلال والنجمه",
    "لافيدتا",
    "SCHOGETTEN",
    "عبد المعبود",
    "المناخلي",
    "بركة",
    "نسكويك",
    "Halawani",
    "tiger",
    "واد فود",
    "نجمه الزيتون",
    "KokI",
    "ميجا",
    "FRESH FARM",
    "بيوفانا",
    "PRINGLES",
    "Nestlé",
    "كتاكيتو الشمعدان",
    "ترايدنت",
    "ابو عوف",
    "CONO",
    "عافية",
    "سلمار",
    "مصريه",
    "تبارك",
    "Brix",
    "اليمنى",
    "Fanta",
    "Tropicana",
    "كندر",
    "Olio",
    "فيشمان ",
    "ايفوني",
    "دسانى",
    "ادد مي",
    "رانى",
    "بسكاتو",
    "توب",
    "أرليكين ",
    "Dolphin ",
    "العيد",
    "Bake Rolz",
    "ايلانو",
    "ايللو",
    "سمارت",
    "M&amp;M",
    "President",
    "Star",
    "بوني",
    "Raslan",
    "أبو كاس",
    "فريش سورس",
    "Deemah",
    "العروسة",
    "دبل",
    "اكوافينا",
    "هارفست",
    "دوبى ديلا",
    "Faragello",
    "الوادي",
    "نستتله",
    "يمامة",
    "ملادرور",
    "بيور لايف",
    "سبينيس",
    "FERSAN",
    "سكرتش",
    "amr ",
    "Mister Potato Crisps",
    "فافنتا",
    "Sunbousse",
    "بيسكاتو",
    "AlKhatib",
    "elano",
    "AL KARAMA",
    "فاست ستار",
    "بوردون",
    "اون",
    "الرشيدى الميزان",
    "كرانشى",
    "قرني",
    "Al Karamah",
    "ITALIANO",
    "ساني",
    "ماجى",
    "شيفى مكس",
    "لونج شيبسى",
    "ويفر",
    "الفا",
    "جوليان",
    "ابتجال",
    "ماكسيل",
    "Activia",
    "سيستيما",
    "توك",
    "دلما",
    "MOLLY S",
    "Doritos",
    "Zee go",
    "Seara",
    "Hayat",
    "نوش",
    "Edita",
    "ابو علي",
    "COLA",
    "Cheeto",
    "تويكس",
    "بيسبو",
    "روتس",
    "بسكو مصر لوكس",
    "تايجر",
    "Fresh Farm",
    "زيجو",
    "كلاس ايه",
    "هديه",
    "HARVEST",
    "جرين لاند",
    "ويتر سبورت",
    "Fiji",
    "الرويدا",
    "الإمارات",
    "Merci",
    "KUNUZ",
    "Delica",
    "Three Chefs",
    "استونيش",
    "شوبيس",
    "نستلة ميجا",
    "Foody ",
    "بريل",
    "VILLARS",
    "Kellogg's Coco Pops",
    "نيلوس",
    "ثرى شفس",
    "ايلو جود فرانس",
    "Imtenan",
    "تاج محل",
    "وادي   فود",
    "باشاك",
    "كافلير",
    "CLASSIC",
    "ميربا",
    "Freska",
    "Rich Bake",
    "فارم فريتس",
    "Tuc",
    "تراست",
    "Crystal",
    "Olivetta ",
    "He Shun Yuan",
    "باساك ",
    "تيست بيور",
    "اوكسي",
    "Abu Auf",
    "Akrat",
    "كوفى بريك",
    "Mirinda",
    "الأطيب",
    "سريراتشا",
    "أميرة",
    "صولو",
    "اولكر",
    "KING'S HAWAIIAN",
    "Roasty",
    "FUNDAY",
    "Gardino",
    "CHEF",
    "المصرين",
    "ستورك ويزرس",
    "منترا",
    "John West",
    "FRESKA",
    "كرستال",
    "الرحاب",
    "مستر بوتيتو",
    "روز جاردن",
    "بنسون",
    "احمد اتي",
    "ميلانجو",
    "باونتي",
    "اديو",
    "بلس دومتي",
    "ابوعوف",
    "فيجيتار",
    "باب الشام",
    "Lactel",
    "El Doha",
    "دانيش",
    "ليبتون",
    "شهى",
    "Fitness",
    "دينا",
    "نصار",
    "Hyperone",
    "Casa Verdi",
    "مورو",
    "نيوتلا",
    "Mutaheda",
    "Americana ",
    "رويال",
    "اف كيو اس",
    "Danette",
    "مونستير",
    "WADI EL NILE",
    "ريحانه",
    "Lays",
    "جيولا",
    "ايلو",
    "جيفركس",
    "OREO",
    "Chamsine",
    "ميرندا",
    "Egy Swiss",
    "عزيمة",
    "باراديس",
    "Meatland",
    "Juhayna",
    "كيندر",
    "بخيرة",
    "تيفانى",
    "كرانشي",
    "ريد بول",
    "عماد افندي",
    "هوم",
    "Breadway",
    "domty",
    "اريال",
    "Kikkoman",
    "جنه",
    "اب جوس",
    "Top Value",
    "Mr Organic",
    "ارت",
    "سبرايت",
    "فيشرمان",
    "Coco Royal",
    "لافشكرى",
    "كيتكات",
    "سكويز",
    "دامفى",
    "ROASTY",
    "Jacker",
    "حدائق كاليفورنيا",
    "سبايسي",
    "المجد",
    "كونو",
    "نسكافية",
    "Up Juice",
    "لاكتيل",
    "Boo Crispy",
    "تمريكان جاردن",
    "النور",
    "Gourmet",
    "ليون",
    "Zam Zam",
    "الشمعدان",
    "Puffitos",
    "مونتانا",
    "الرشيدى الاصلى",
    "مونجنيز",
    "امستل رادلر",
    "دوبيلا",
    "sunshine",
    "تيفاني ايفريداي",
    "وادي فود ",
    "تويننجز",
    "هاواي",
    "Akizay",
    "الملكه",
    "واينز",
    "مكفتيز",
    "بسكريم مكفتيز",
    "لافاش كيري",
    "ضياء",
    "توب شيف",
    "Masreya",
    "نسلي",
    "شاهين",
    "جبنتي",
    "Aqua Delta",
    "ص شاين",
    "الهدهد",
    "Obour Land",
    "الخطيب",
    "Sriracha",
    "فارم تشيز",
    "Kit Kat",
    "فارفيللو",
    "Tourist",
    "ارلوى ارثر",
    "رو",
    "Shahd",
    "بسنت شيراتون",
    "El Zahar",
    "NOLITO",
    "فارمرز",
    "بريد واي",
    "بسكاتو دايجستا",
    "لايون",
    "Sunshine",
    "ريتش باك",
    "بيبسي",
    "FRESHLY",
    "حلوب الخير",
    "CHICKETITA",
    "بسكو مصر",
    "لورباك",
    "cocacola",
    "Royal",
    "ديساني",
    "بيفى",
    "Americana",
    "سيدرا ",
    "إريال",
    "ثري شيف",
    "Diatosta",
    "فريش فارم/",
    "Go Mix",
    "نستله",
    "KALBAZ",
    "جهينة",
    "ماجيك مومنتس",
    "Ritter Sport",
    "اجا",
    "لوكس",
    "شيفى",
    "dasani",
    "بريزيدن",
    "اللحيمى",
    "كارفور",
    "Tiffany",
    "كادبرى",
    "Shaheen",
    "Tiffany Break",
    "LHEMY",
    "هانز",
    "بون اروما",
    "امريكان جاردن",
    "الاطباء",
    "الطاوس",
    "بيك  رولز",
    "مكفيتز",
    "Millers",
    "كنانة",
    "الطحان",
    "دوبيللا",
    "نسكلفيه",
    "امريكانا ",
    "TIGER",
    "Ulker Biskrem",
    "اسناد",
    "Puvana",
    "Rani",
    "رانشيتو",
    "Bahlsen",
    "DAVIDOFF",
    "الساعة",
    "بونكي",
    "كوكو رويال",
    "KitKat",
    "تشويس",
    "General",
    "صن بايتس",
    "Walkers",
    "تريفا",
    "قمرنا",
    "امريكانو",
    "Today",
    "فريسكا",
    "صانشاين",
    "ميتكو",
    "Maggi",
    "احمد",
    "حلوه",
    "fanta",
    "اورينت",
    "Due Vittorie",
    "تاى وو",
    "اللحيمي",
    "كريم",
    "El Maleka",
    "ايه ار ام",
    "تانك",
    "اولكر هالي",
    "Mentos",
    "شويبس",
    "Tabarak",
    "Nestle",
    "Tutti Frutti",
    "الكبوس",
    "رتش بيك",
    "ماكفيتيز",
    "بوردن",
    "Mega",
    "تليجر",
    "المناهري",
    "كابوس",
    "سويت لايف",
    "الشروق",
    "الكرامة",
    "كمفورت",
    "سفره",
    "فينوس",
    "ويرمان",
    "Temry",
    "Nahrain",
    "هابي بيض",
    "Halls",
    "المكلكه",
    "البطريق",
    "صنى",
    "الساعه",
    "ديري",
    "Maggi ",
    "هاينز",
    "فن داى",
    "ترايدينت",
    "BUZZ",
    "نستله نسكويك",
    "الهلال",
    "KATAKITO",
    "فلافور فورس",
    "غارم فريتس",
    "لواكر",
    "ميلكي",
    "بيفي",
    "Biscato",
    "EL WATANIA",
    "Lindt",
    "Smart",
    "شوبا",
    "العبد",
    "روشن",
    "كيو",
    "حلواني",
    "ويست",
    "لايف جرين بريتزل",
    "نوش نوش",
    "وادي فود",
    "Optifast",
    "العميد",
    "شيبسي فورنو",
    "فيرو",
    "مولتو",
    "توينينجز",
    "كوفي ميكس",
    "نيدو",
    "ثرى ام",
    "جالكسي",
    "Fresh",
    "Goldalex",
    "ديليكا",
    "فلاينج جوس",
    "Swiss",
    "TIFFANY",
    "بريك تى",
    "العروبة",
    "دومتي",
    "ضحي",
    "فانتا",
    "تيفاني هابي بريك",
    "كيلوجز",
    "اكتيفيا",
    "سوبر فودز",
    "bounty",
    "كادبوي",
    "نستله مينيز",
    "بلو دراجون",
    "Mimix",
    "Feba",
    "كوفرتينا",
    "هدية",
    "ابتهال",
    "طعمه",
    "هانــز",
    "شتورة شتورة",
    "البستاني ",
    "Lamar",
    "Barilla",
    "KNORR",
    "شمعدان",
    "American Eagles",
    "ريف صابح",
    "أنديا ميلانو",
    "فاكيتنا",
    "شيفي ميكس",
    "هايبنز",
    "سي دي ام",
    "فانيش",
    "Trident",
    "صني",
    "METCO",
    "Qalia",
    "Lion",
    "كلاسيك سناكس",
    "بركه",
    "أبو علي",
    "Vegeta",
    "عبور لاند",
    "امريكانا",
    "Zamzam",
    "صول",
    "Wadi ",
    "وندر فيل",
    "الزهار",
    "تايد",
    "Al Adham",
    "the meat farm",
    "Spinneys",
    "Chefy",
    "هول ويت",
    "فارم فريش",
    "McVities",
    "Dina",
    "ليز",
    " حدائق كاليفورنيا",
    "الشيف الذهبي",
    "إيليت",
    "Froots",
    "هوهوز",
    "Bonjorno",
    "صافي،",
    "الوطنية",
    "Al-Kbous",
    "ميانتا",
    "Dobella",
    "الخير",
    "DIGESTIVE",
    "Prima",
    "الفرسان",
    "بسكو مصر كوكو لافرز",
    "Heinz ",
    "كاتشى",
    "النجمه",
    "فيلارز",
    "AlWatania",
    "Mcvities",
    "ماجيكال",
    "برايم",
    "كاليفورنيا",
    "بيج شيبس",
    "المروة ",
    "فريماز",
    "سيريل",
    "يمامه",
    "بيورتي",
    "استرس",
    "ويندكس",
    "Beyti",
    "دريا ",
    "Aquafina",
    "بساطه",
    "Safcol ",
    "سفرجي",
    "صن شاين",
    "أطياب",
    "المراكبي",
    "MENTOS",
    "بوك",
    "Pepsi",
    "لفتح",
    "Gastone Lago Mini",
    "بريفا",
    "تشويس ",
    "Mazola",
    "المطبخ المصرى",
    "Kinder",
    "بستو",
    "ثري شفس",
    "الربيع",
    "زمزم",
    "يارو",
    "مكفيتز دايجستيف",
    "ميلكمان",
    "FARGELLO",
    "Chicketita",
    "Maxell",
    "سكوتش برايت",
    "Sofra",
    "كيري",
    "فوكس",
    "ستورك",
    "الضحى",
    "نمرة 1",
    "بلو ريفا",
    "Hintz",
    "مارلو",
    "نور",
    "لويكر",
    "سبيبنس",
    "Werther's original",
    "Bake Land",
    "Viva",
    "Elleheimy",
    "بيبتو",
    "ماجيك مومنت",
    "Orouba",
    "Milka",
    "برسيل",
    "كيتشين اكسبريس",
    "بست",
    "MEGA CHIPS",
    "Almarai",
    "برافو",
    "سيليكو",
    "الجوهرة",
    "متوكل",
    "Squeeze",
    "ريسيز",
    "Dots",
    "قشطة",
    "nestle",
    "احمد تي",
    "Frico",
    "Tashkila ",
    "شهر زاد",
    "اكسلانت",
    "Agromonte",
    "جوليو",
    "تشيزا",
    "Chefy Mix",
    "ماندولين",
    "باتاك",
    "Yahoo",
    "Gimoka",
    "فالي دل سولي",
    "جورمى",
    "اولفيتا",
    "قلية",
    "Jewels",
    "abu auf",
    "بريك",
    "جلاكسى",
    "THREE CHEFS",
    "كواليتي",
    "لاجو",
    "راني",
    "تشكيلة",
    "حدائق",
    "كوين",
    "Mokate",
    "سويت اند ساور",
    "كادبري",
    "ملكي لاند",
    "Segafredo",
    "دايجيستف",
    "امتنان",
    "فروتى",
    "هابي",
    "أمريكان جاردن",
    "Hit",
    "Danone",
    "الاطيب",
    "الوطنيه",
    "WINDEX",
    "كولد استون",
    "دافيدوف",
    "FQS ",
    "Miro",
    "ليبتن",
    "Mora",
    "الكرمه",
    "Sunshine ",
    "Classic",
    "كوكو لافرز",
    "الرفاعى",
    "El-Maleka",
    "توب فاليو",
    "SHAHD",
    "وادى فود",
    "مايا",
    "بليدج",
    "ستار",
    "العابد ",
    "كيت كات",
    "ابو الليل",
    "بخيره",
    "Ottima",
    "القصر",
    "شيبسي تايجر",
    "حياة",
    "داونى",
    "الصحابة",
    "لافازا",
    "I Salt",
    "دومتى",
    "PRESIDENT",
    "ليندت",
    "My Tuna",
    "Fersan",
    "ثرى شيفس",
    "ويندز",
    "Dasany",
    "موسي",
    "Wadi Food",
    "Avanti",
    "ارلكين",
    "Soignon",
    "CocaCola",
    "Tai Hua",
    "الوفاء",
    "جيموكا",
    "Batook",
    "كيان",
    "Lavache Quirit",
    "ماكفيتيز دايجيستيف",
    "Ketonista",
    "Halwani",
    "براغ",
    "غاليه",
    "الصقر",
    "فروتس",
    "Al Suhagy",
    "كلاس اية60جم",
    "Mazaq",
    "بيبيتو",
    "كولافيتا",
    "ZamZam",
    "مستر كريسبس",
    "بورجيس",
    "بسكو مصر كاكاو لافرز",
    "TWININGS",
    "ميجو",
    "ElMaleka",
    "الاندلس",
    "بالسن ديليس ",
    "Demia",
    "دانو",
    "Nido",
    "Good day",
    "OLIO",
    "مونجينى",
    "Twinings",
    "ويف",
    "اوكسى",
    "شيكيتيتا",
    "جاكر",
    "ترى تى",
    "Vimto",
    "pepsi",
    "Sheikh EL-Attareen",
    "برايم فودز",
    "Moms Food",
    "MAYA",
    "Calnort",
    "شيتوس",
    "Baraka",
    "ديري ميلك",
    "هولز",
    "عامر",
    "تانج",
    "Pretzo",
    "خير وبركه",
    "Ferrero",
    "كاتشي",
    "هوت اند كريسبي",
    "CALNORT ",
    "Tala",
    "Daria ",
    "coca cola",
    "بريدواي",
    "أكيثاي",
    "جريسيني",
    "El Bawadi",
    "Herman",
    "مافا",
    "جاج",
    "العين",
    "خير بلدنا",
    "اسبريت",
    "FITNESS",
    "فروتوريا",
    "دكتور بيبر",
    "Fruitoria",
    "فودي",
    "لوكر",
    "سنيكرز",
    "مذاق",
    "سالوتى",
    "ابومازن",
    "مودريشن",
    "سبايسى",
    "كافي ميكس",
    "Persil",
    "صن توب",
    "وفير",
    "مولز",
    "Farazah",
    "ساتش",
    "Panda",
    "جود داي",
    "ثري شيف،",
    "SAFI",
    "BAKE ROLZ",
    "تودو",
    "Ion",
    "NFI Emirates Pofaki",
    "California Garden"
}


from dotenv import load_dotenv
